<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="robot">
    <!-- Model macros -->
    <xacro:macro name="wheel" params="prefix X Y wheel_joint_type friction_coeff:=0.2">
        <joint name="${prefix}_WHEEL_JOINT" type="${wheel_joint_type}">
            <parent link="${base_link_name}" />
            <child link="${prefix}_WHEEL" />
            <origin xyz="${X} ${Y} ${wheelHeight - chassisHeight/2.0}" rpy="-${0.5*M_PI} 0 0" />
            <axis xyz="0 0 1" rpy="0 0 0" />
            <dynamics damping="1.0" friction="0.0" />
            <limit effort="100" velocity="10" />
            <joint_properties damping="0.2" friction="0.2" />
        </joint>

        <link name="${prefix}_WHEEL">
            <collision>
                <origin xyz="0 0 0" rpy="0 0 0" />
                <geometry>
                    <cylinder length="${wheelWidth/10}" radius="${wheelRadius}" />
                </geometry>
            </collision>
            <visual>
                <origin xyz="0 0 0" rpy="1.570796 0  0" />
                <geometry>
                    <mesh filename="file://$(find robot_description)/urdf/meshes/wheel.dae" />
                </geometry>
            </visual>
            <inertial>
                <origin xyz="0 0 0" rpy="0 0 0" />
                <mass value="${wheelMass}" />
                <xacro:cylinder_inertia m="${wheelMass}" r="${wheelRadius}" h="${wheelWidth}" />
            </inertial>
        </link>

        <gazebo reference="${prefix}_WHEEL">
            <mu1 value="${friction_coeff}" />
            <mu2 value="${friction_coeff}" />
            <fdir1 value="1 0 0" />
            <kp>10000000.0</kp>
            <kd>1.0</kd>
            <minDepth>0.005</minDepth>
            <maxVel>100.0</maxVel>
            <material>Gazebo/DarkGrey</material>
        </gazebo>
    </xacro:macro>

    <xacro:macro name="chassis">
        <link name="${base_link_name}">
            <collision>
                <origin xyz="0 0 0" rpy="0 0 0" />
                <geometry>
                    <box size="${chassisLength} ${chassisWidth} ${chassisHeight}" />
                </geometry>
            </collision>
            <visual>
                <origin xyz="0 0 0" rpy="0 0 0" />
                <geometry>
                    <box size="${chassisLength} ${chassisWidth} ${chassisHeight}" />
                </geometry>
                <material name="base_material">
                    <color rgba="0.8 0.0 0.1 1.0" />
                </material>
            </visual>
        </link>

        <link name="top">
            <collision>
                <origin xyz="${topXOffset} 0 0" rpy="0 0 0" />
                <geometry>
                    <box size="${topLength} ${topWidth} ${topHeight}" />
                </geometry>
            </collision>
            <visual>
                <origin xyz="${topXOffset} 0 0" rpy="0 0 0" />
                <geometry>
                    <box size="${topLength} ${topWidth} ${topHeight}" />
                </geometry>
            </visual>
        </link>

        <gazebo reference="top">
            <material>Gazebo/Grey</material>
        </gazebo>

        <gazebo reference="${base_link_name}">
            <material>Gazebo/Red</material>
        </gazebo>

        <joint name="top_to_base_link" type="fixed">
            <parent link="${base_link_name}" />
            <child link="top" />
            <origin xyz="0.0 0.0 ${chassisHeight/2.0}" rpy="0 0 0" />
        </joint>

        <!-- Fixed joint to add dummy inertia link -->
        <joint name="base_to_base_inertia" type="fixed">
            <parent link="${base_link_name}" />
            <child link="base_inertia" />
            <origin xyz="0 0 0" rpy="0 0 0" />
        </joint>

        <!-- Dummy inertia link, because KDL cannot have inertia on the base link -->
        <link name="base_inertia">
            <inertial>
                <origin xyz="0 0 0" rpy="0 0 0" />
                <mass value="${chassisMass}" />
                <xacro:box_inertia m="${chassisMass}"
                    x="${chassisLength}"
                    y="${chassisWidth}"
                    z="${chassisHeight}" />
            </inertial>
        </link>

        <link name="top_extension">
            <collision>
                <origin xyz="0 0 0" rpy="0 0 0" />
                <geometry>
                    <box size="${topExtensionLength/3} ${topExtensionWidth} ${topExtensionHeight}" />
                </geometry>
            </collision>
            <visual>
                <origin xyz="0 0 0" rpy="0 0 0" />
                <geometry>
                    <box size="${topExtensionLength/3} ${topExtensionWidth} ${topExtensionHeight}" />
                </geometry>
                <material name="extension_material">
                    <color rgba="0.0 0.0 1.0 1.0" /> <!-- Blue -->
                </material>
            </visual>
        </link>

        <gazebo reference="top_extension">
            <material>Gazebo/Blue</material>
        </gazebo>

        <joint name="top_extension_to_top" type="fixed">
            <parent link="top" />
            <child link="top_extension" />
            <origin xyz="-${topExtensionLength/3} 0 0.1" rpy="0 0 0" />
        </joint>

    </xacro:macro>

    <xacro:macro name="robot" params="wheel_joint_type:=continuous">
        <xacro:chassis />

        <xacro:wheel prefix="LF" X="${frontWheelX}"
            Y="${chassisWidth/2+wheelClearance+wheelWidth/2}"
            wheel_joint_type="${wheel_joint_type}"
            friction_coeff="0.7" />

        <xacro:wheel prefix="RF" X="${frontWheelX}"
            Y="${-chassisWidth/2-wheelClearance-wheelWidth/2}"
            wheel_joint_type="${wheel_joint_type}"
            friction_coeff="0.7" />

        <xacro:wheel prefix="LH" X="${backWheelX}"
            Y="${chassisWidth/2+wheelClearance+wheelWidth/2}"
            wheel_joint_type="${wheel_joint_type}"
            friction_coeff="0.7" />

        <xacro:wheel prefix="RH" X="${backWheelX}"
            Y="${-chassisWidth/2-wheelClearance-wheelWidth/2}"
            wheel_joint_type="${wheel_joint_type}"
            friction_coeff="0.7" />

        <!-- broadcast model state -->
        <gazebo>
            <plugin filename="gz-sim-pose-publisher-system" name="gz::sim::systems::PosePublisher">
                <publish_link_pose>false</publish_link_pose>
                <publish_nested_model_pose>true</publish_nested_model_pose>
                <update_frequency>50</update_frequency>
            </plugin>
        </gazebo>
    </xacro:macro>

    <xacro:include filename="$(find robot_description)/urdf/imu.urdf.xacro" />

    <!-- TODO Include the lidar mount and gazebo laser scan sensor xacro files and instantiate them -->
    <!-- Attached lidar mount link to the base link and add lidar sensor plugin to the lidar sensor frame -->
</robot>